version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: coffee-api_db
    environment:
      MYSQL_USER: coffee_user
      MYSQL_ROOT_PASSWORD: verysecret
      MYSQL_DATABASE: coffee-api_db
      MYSQL_PASSWORD: coffee_password
    ports:
      - "3307:3306"
    networks:
      - coffee-api_network
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: linuxserver/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: verysecret
    ports:
      - "8888:80"
    networks:
      - coffee-api_network
    depends_on:
      - mysql

networks:
  coffee-api_network:
    driver: bridge

volumes:
  db_data:
    driver: local