services:
  mysql:
    image: mysql:latest
    container_name: coffee-api_db
    environment:
      MYSQL_USER: coffee_user
      MYSQL_ROOT_PASSWORD: verysecret
      MYSQL_DATABASE: coffee-api_db
      MYSQL_PASSWORD: coffee_password
    ports:
      - "3307:3306"
    networks:
      - coffeeapinet
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: linuxserver/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: verysecret
    ports:
      - "8888:80"
    networks:
      - coffeeapinet
    depends_on:
      - mysql

  coffee-api:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8080:8080"
    networks:
      - coffeeapinet
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/coffee-api_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: verysecret

networks:
  coffeeapinet:

volumes:
  db_data:
    driver: local